version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd api
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run knex:migrate
            - run: npm run knex:seed
            - run: npm run prod
workflows:
    build-and-run:
      jobs:
        - build-and-run